services:
  - type: web
    name: roofroot-backend
    env: node
    plan: free
    rootDir: roofroot-backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 